/* Canvas presentation lives outside immutable Agent configurations. */
const CanvasMath={
  point:(x,y,v)=>({x:(x-v.x)/v.zoom,y:(y-v.y)/v.zoom}),
  zoomAt(v,factor,x,y){const p=this.point(x,y,v),zoom=Math.max(.25,Math.min(2,v.zoom*factor));return {x:x-p.x*zoom,y:y-p.y*zoom,zoom}},
  connectionError(c,from,to,port){const n=c.nodes.find(n=>n.id===from),target=c.nodes.find(n=>n.id===to);if(!n||!target)return '节点不存在';if(from===to)return '不能连接自身';if(target.type==='input')return '输入节点不能接收入线';if(n.type==='output')return '输出节点没有出口';if(port==='error'){if(!['model','tool','knowledge','validate','service'].includes(n.type))return '该节点没有异常出口';if(target.type!=='fallback')return '异常出口请连接人工 / 保底节点';if(n.fallback===to)return '该异常出口已连接此节点'}else{if(n.type==='condition'?!['yes','no'].includes(port):port!=='next')return '请选择有效出口';if(c.edges.some(e=>e.from===from&&e.port===port))return '该出口已有连线，请先删除原连线'}let seen=new Set();function reaches(id){if(id===from)return true;if(seen.has(id))return false;seen.add(id);let next=c.edges.filter(e=>e.from===id).map(e=>e.to),fallback=c.nodes.find(n=>n.id===id)?.fallback;if(fallback)next.push(fallback);return next.some(reaches)}return reaches(to)?'不能形成循环，一期仅支持顺序与条件流程':''}
};
let canvasGesture=null,canvasPending=null,canvasSelectedEdge=null,canvasSpace=false;
const originalFlow=flow,originalRender=render;
function canvasState(){S.canvasLayouts=S.canvasLayouts||{};return S.canvasLayouts[appId]||(S.canvasLayouts[appId]={positions:{},view:{x:30,y:40,zoom:.75}})}
function canvasPosition(n,i){const layout=canvasState();if(!layout.positions[n.id]){const known={in:[20,30],data:[310,30],search:[600,30],branch:[600,220],llm:[310,220],fallback:[890,220],check:[310,410],out:[600,410],ctx:[310,30],kb:[600,30],intent:[600,220],logistics:[890,410]};let p=known[n.id]||[40+(i%3)*290,30+Math.floor(i/3)*185];layout.positions[n.id]={x:p[0],y:p[1]}}return layout.positions[n.id]}
function canvasPorts(n){if(n.type==='output')return [];let list=n.type==='condition'?[['yes','是'],['no','否']]:[['next','输出']];if(['model','tool','knowledge','validate','service'].includes(n.type))list.push(['error','异常']);return list}
function canvasPortXY(id,port){let n=cfg().nodes.find(n=>n.id===id),p=canvasPosition(n,cfg().nodes.indexOf(n));if(port==='in')return {x:p.x,y:p.y+43};if(port==='error')return {x:p.x+110,y:p.y+108};return {x:p.x+220,y:p.y+(port==='no'?78:43)}}
function canvasNode(n,i){let p=canvasPosition(n,i);return `<div class="graph-node ${n.id===nodeId?'selected':''} ${lastRun?.appId===appId&&lastRun.steps.some(s=>s.id===n.id)?'executed':''}" data-node="${n.id}" style="left:${p.x}px;top:${p.y}px" tabindex="0" role="button" aria-label="节点 ${esc(n.name)}"><span class="node-type">${icon(n.type==='model'?'spark':n.type==='tool'?'tool':'box')}${E.types[n.type]}</span><b>${esc(n.name)}</b><small>${esc(n.id)}</small>${n.type!=='input'?`<button class="graph-port input-port" data-port="in" data-node="${n.id}" aria-label="${esc(n.name)} 输入端口" title="输入：拖入连线或点击完成连接"></button>`:''}${canvasPorts(n).map(([port,label])=>`<button class="graph-port output-port port-${port}" data-port="${port}" data-node="${n.id}" aria-label="${esc(n.name)} ${label}端口" title="${label}：拖到目标输入端口，也可点击后再点击目标"><span>${label}</span></button>`).join('')}</div>`}
flow=function(c){let html=originalFlow(c),start=html.indexOf('<section class="canvas">'),end=html.indexOf('<aside class="node-inspector">',start);let stage=`<section class="graph-panel"><div class="graph-toolbar"><b>执行流程 <small>${c.nodes.length} 节点</small></b><div class="graph-tools"><button onclick="canvasZoom(.8)" aria-label="缩小画布">−</button><span id="canvas-zoom">75%</span><button onclick="canvasZoom(1.25)" aria-label="放大画布">+</button><button onclick="canvasFit()">适应</button><button onclick="canvasActual()">100%</button><button onclick="canvasExpand()" aria-label="展开画布">⛶</button></div></div><div id="graph-viewport" tabindex="0" role="region" aria-label="流程画布，拖动节点或空白区域，滚轮缩放"><div id="graph-world"><svg id="graph-edges" aria-label="流程连线"><defs><marker id="graph-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="#a193c9"/></marker></defs><g id="graph-edge-paths"></g><path id="graph-preview" fill="none" stroke="#8d73da" stroke-width="2.5" stroke-dasharray="7 5"/></svg>${c.nodes.map(canvasNode).join('')}</div>${!c.nodes.length?'<div class="graph-empty">从左侧添加节点，再拖动端口连接</div>':''}<div id="graph-edge-action" hidden></div></div><div class="graph-hint" id="graph-hint">拖动节点移动 · 拖动空白平移 · 滚轮缩放 · 端口拖线或点选连接</div><details class="graph-edge-list"><summary>连线列表 / 精确连接</summary><div class="connections">${c.edges.map((e,i)=>`<div class="connection"><span>${esc(e.from)} → ${esc(e.to)} · ${e.port}</span><button class="plain" onclick="removeEdge(${i})" aria-label="删除连线 ${e.from} 到 ${e.to}">×</button></div>`).join('')}</div>${button('表单连接节点','connectDialog()','small')}</details></section>`;return html.slice(0,start)+stage+html.slice(end)};
render=function(){const expanded=document.querySelector('.canvas-expanded');originalRender();if(expanded)document.querySelector('.flow-editor')?.classList.add('canvas-expanded');canvasMount()};
function canvasMount(){const viewport=document.querySelector('#graph-viewport');if(!viewport)return;canvasGesture=null;canvasSelectedEdge=null;canvasPending=null;canvasTransform();canvasDraw();viewport.addEventListener('pointerdown',canvasDown);viewport.addEventListener('pointermove',canvasMove);viewport.addEventListener('pointerup',canvasUp);viewport.addEventListener('pointercancel',canvasCancel);viewport.addEventListener('wheel',e=>{e.preventDefault();const r=viewport.getBoundingClientRect();canvasState().view=CanvasMath.zoomAt(canvasState().view,Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);canvasTransform();canvasPersistView()}, {passive:false});viewport.addEventListener('keydown',canvasKey);viewport.addEventListener('contextmenu',e=>e.preventDefault());}
function canvasTransform(){const v=canvasState().view,world=document.querySelector('#graph-world'),viewport=document.querySelector('#graph-viewport');if(!world)return;world.style.transform=`translate(${v.x}px,${v.y}px) scale(${v.zoom})`;viewport.style.backgroundSize=`${22*v.zoom}px ${22*v.zoom}px`;viewport.style.backgroundPosition=`${v.x}px ${v.y}px`;document.querySelector('#canvas-zoom').textContent=Math.round(v.zoom*100)+'%';document.querySelector('#graph-edge-action').hidden=true;}
function canvasCurve(a,b,error=false){if(error)return `M${a.x} ${a.y} C${a.x} ${a.y+85},${b.x-80} ${b.y},${b.x} ${b.y}`;let d=Math.max(65,Math.abs(b.x-a.x)*.45);return `M${a.x} ${a.y} C${a.x+d} ${a.y},${b.x-d} ${b.y},${b.x} ${b.y}`}
function canvasEdges(){let c=cfg();return [...c.edges.map((e,i)=>({...e,key:'edge:'+i})),...c.nodes.filter(n=>n.fallback).map(n=>({from:n.id,to:n.fallback,port:'error',key:'error:'+n.id}))].filter(e=>c.nodes.some(n=>n.id===e.from)&&c.nodes.some(n=>n.id===e.to))}
function canvasDraw(){let group=document.querySelector('#graph-edge-paths');if(!group)return;group.innerHTML=canvasEdges().map(e=>{let a=canvasPortXY(e.from,e.port),b=canvasPortXY(e.to,'in'),path=canvasCurve(a,b,e.port==='error'),label={yes:'是',no:'否',error:'异常'}[e.port]||'';return `<g class="graph-edge ${e.port==='error'?'error-edge':''} ${canvasSelectedEdge===e.key?'selected':''}" data-edge="${e.key}"><path class="edge-hit" d="${path}"/><path class="edge-visible" d="${path}" marker-end="url(#graph-arrow)"/>${label?`<text x="${a.x+(e.port==='error'?8:20)}" y="${a.y+(e.port==='error'?25:-9)}">${label}</text>`:''}</g>`}).join('')}
function canvasEditable(){if(S.role==='业务编辑者')return true;toast('请切换业务编辑者调整节点或连线');return false}
function canvasSelect(id){nodeId=id;document.querySelectorAll('.graph-node').forEach(el=>el.classList.toggle('selected',el.dataset.node===id));const n=cfg().nodes.find(n=>n.id===id);document.querySelector('.node-inspector').innerHTML='<h3>节点配置</h3>'+nodeForm(n,cfg());}
function canvasDown(e){if(e.target.closest('#graph-edge-action'))return;if(e.button!==0&&e.button!==1)return;const viewport=e.currentTarget;viewport.focus({preventScroll:true});let port=e.target.closest('[data-port]'),node=e.target.closest('.graph-node'),edge=e.target.closest('[data-edge]');e.preventDefault();if(canvasSpace||e.button===1){canvasStartPan(e);return}if(port){if(!canvasEditable())return;if(port.dataset.port==='in'){if(canvasPending)canvasFinishLink(port.dataset.node);return}canvasPending={from:port.dataset.node,port:port.dataset.port};canvasGesture={type:'link',startX:e.clientX,startY:e.clientY,moved:false};viewport.setPointerCapture(e.pointerId);canvasHint('拖到目标节点左侧输入端口；也可松开后点击输入端口。Esc 取消');return}if(node){if(!canvasEditable())return;canvasSelect(node.dataset.node);let p=canvasState().positions[node.dataset.node];canvasGesture={type:'node',id:node.dataset.node,startX:e.clientX,startY:e.clientY,x:p.x,y:p.y,moved:false};viewport.setPointerCapture(e.pointerId);return}if(edge){canvasSelectedEdge=edge.dataset.edge;canvasDraw();canvasEdgeAction(e.clientX,e.clientY);return}canvasPending=null;document.querySelector('#graph-preview').setAttribute('d','');canvasSelectedEdge=null;canvasDraw();canvasStartPan(e)}
function canvasStartPan(e){canvasGesture={type:'pan',startX:e.clientX,startY:e.clientY,x:canvasState().view.x,y:canvasState().view.y};e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.classList.add('panning')}
function canvasMove(e){const viewport=e.currentTarget,g=canvasGesture;if(!g){if(canvasPending)canvasPreview(e);return}let dx=e.clientX-g.startX,dy=e.clientY-g.startY;if(Math.abs(dx)+Math.abs(dy)>3)g.moved=true;if(g.type==='pan'){canvasState().view.x=g.x+dx;canvasState().view.y=g.y+dy;canvasTransform()}if(g.type==='node'){let p=canvasState().positions[g.id];p.x=g.x+dx/canvasState().view.zoom;p.y=g.y+dy/canvasState().view.zoom;const el=document.querySelector(`.graph-node[data-node="${g.id}"]`);el.style.left=p.x+'px';el.style.top=p.y+'px';canvasDraw()}if(g.type==='link')canvasPreview(e)}
function canvasPreview(e){if(!canvasPending)return;const r=document.querySelector('#graph-viewport').getBoundingClientRect(),b=CanvasMath.point(e.clientX-r.left,e.clientY-r.top,canvasState().view),a=canvasPortXY(canvasPending.from,canvasPending.port);document.querySelector('#graph-preview').setAttribute('d',canvasCurve(a,b,canvasPending.port==='error'));document.querySelectorAll('.input-port').forEach(p=>p.classList.remove('port-target'));const hover=document.elementFromPoint(e.clientX,e.clientY)?.closest('.input-port');if(hover)hover.classList.add('port-target')}
function canvasUp(e){const g=canvasGesture;if(!g)return;canvasGesture=null;e.currentTarget.classList.remove('panning');if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(g.type==='link'&&g.moved){let port=document.elementFromPoint(e.clientX,e.clientY)?.closest('.input-port');if(port)canvasFinishLink(port.dataset.node);else{canvasPending=null;document.querySelector('#graph-preview').setAttribute('d','');canvasHint('未连接：请将连线拖到目标节点左侧输入端口。')}}else if(g.type==='node'||g.type==='pan'){persist();if(g.type==='node'&&g.moved)canvasHint('节点布局已自动保存，不改变行为版本或评测结果。')}document.querySelectorAll('.port-target').forEach(p=>p.classList.remove('port-target'))}
function canvasFinishLink(target){let p=canvasPending;if(!p)return;let error=CanvasMath.connectionError(cfg(),p.from,target,p.port);canvasPending=null;document.querySelector('#graph-preview').setAttribute('d','');if(error){toast(error);canvasHint(error);return}if(p.port==='error')cfg().nodes.find(n=>n.id===p.from).fallback=target;else cfg().edges.push(E.edge(p.from,target,p.port));dirty=true;canvasSelectedEdge=null;render();canvasHint('连线已添加。请保存草稿、静态检查后重新固化与评测。')}
function canvasEdgeAction(clientX,clientY){const viewport=document.querySelector('#graph-viewport'),r=viewport.getBoundingClientRect(),el=document.querySelector('#graph-edge-action');el.hidden=false;el.style.left=Math.max(8,Math.min(clientX-r.left,viewport.clientWidth-140))+'px';el.style.top=Math.max(8,Math.min(clientY-r.top,viewport.clientHeight-45))+'px';el.innerHTML='<button onclick="canvasDeleteEdge(event)">删除选中连线 ×</button>';}
function canvasDeleteEdge(e){e?.stopPropagation();if(!canvasEditable()||!canvasSelectedEdge)return;let [type,id]=canvasSelectedEdge.split(':');if(type==='error')cfg().nodes.find(n=>n.id===id).fallback='';else cfg().edges.splice(+id,1);canvasSelectedEdge=null;dirty=true;render();canvasHint('连线已删除，请保存草稿并重新检查。')}
function canvasCancel(){canvasGesture=null;canvasPending=null;document.querySelector('#graph-preview')?.setAttribute('d','');document.querySelector('#graph-viewport')?.classList.remove('panning')}
function canvasHint(text){const el=document.querySelector('#graph-hint');if(el)el.textContent=text}
function canvasKey(e){if(e.target.closest('input,textarea,select'))return;if(e.code==='Space'){e.preventDefault();canvasSpace=true}if(e.key==='Escape'){canvasCancel();canvasHint('连接已取消')}if((e.key==='Delete'||e.key==='Backspace')&&canvasSelectedEdge){e.preventDefault();canvasDeleteEdge(e)}if((e.key==='Enter'||e.key===' ')&&e.target.matches('.graph-port')){e.preventDefault();const p=e.target;if(p.dataset.port==='in')canvasFinishLink(p.dataset.node);else if(canvasEditable()){canvasPending={from:p.dataset.node,port:p.dataset.port};canvasHint('请点击目标输入端口，或用 Tab 选中后按 Enter')}}}
document.addEventListener('keyup',e=>{if(e.code==='Space')canvasSpace=false});window.addEventListener('blur',()=>{canvasSpace=false;canvasCancel()});
function canvasPersistView(){clearTimeout(window.canvasSave);window.canvasSave=setTimeout(persist,200)}
function canvasZoom(factor){const v=document.querySelector('#graph-viewport');canvasState().view=CanvasMath.zoomAt(canvasState().view,factor,v.clientWidth/2,v.clientHeight/2);canvasTransform();persist()}
function canvasActual(){canvasZoom(1/canvasState().view.zoom)}
function canvasFit(){const viewport=document.querySelector('#graph-viewport');if(!cfg().nodes.length)return;let ps=cfg().nodes.map(canvasPosition),minX=Math.min(...ps.map(p=>p.x)),minY=Math.min(...ps.map(p=>p.y)),w=Math.max(...ps.map(p=>p.x))+240-minX,h=Math.max(...ps.map(p=>p.y))+125-minY,zoom=Math.max(.25,Math.min(1.1,(viewport.clientWidth-50)/w,(viewport.clientHeight-70)/h));canvasState().view={x:(viewport.clientWidth-w*zoom)/2-minX*zoom,y:(viewport.clientHeight-h*zoom)/2-minY*zoom,zoom};canvasTransform();persist()}
function canvasExpand(){document.querySelector('.flow-editor').classList.toggle('canvas-expanded');canvasFit()}
// Refresh node labels and visual error edges without remounting the active field.
const canvasOriginalEdit=editNode;editNode=function(k,v){canvasOriginalEdit(k,v);const n=cfg().nodes.find(n=>n.id===nodeId),el=document.querySelector(`.graph-node[data-node="${nodeId}"] b`);if(el)el.textContent=n.name;canvasDraw()};
render();

// Review extensions loaded after the base UI so they remain compatible with the canvas override.
if(typeof evaluation==='function'){const baseEvaluation=evaluation;evaluation=function(){const a=app(),d=(S.datasets||[]).find(x=>x.id===a.dataset);let html=baseEvaluation();html=html.replace(`<div class="review-toolbar">`,`<div class="review-toolbar"><div class="dataset-summary"><b>当前数据集</b><span>${esc(a.dataset)}</span><small>${d?esc(d.name)+' · '+d.count+' 条 · '+d.format:'固定人工标签 · 500 条'}</small></div><div class="actions">${button('上传数据集','datasetUpload()','small')}</div>`);html=html.replace(/数据集 [^<]+<\/b><small>固定人工标签 · 500 条 · 门槛/,`数据集 ${esc(a.dataset)}</b><small>${d?esc(d.name)+' · '+d.count+' 条 · '+d.format:'固定人工标签 · 500 条'} · 门槛`);return html+evalTasks()};render()}


