/* PRD V1.3: deterministic demo domain model. No real services are called. */
(function(root){
const copy=x=>JSON.parse(JSON.stringify(x));
const types={input:'输入',output:'输出',model:'模型',knowledge:'知识检索',tool:'工具调用',condition:'条件判断',data:'数据处理',context:'上下文',validate:'校验',fallback:'人工 / 保底出口',service:'受控服务'};
const node=(id,type,name,map='input.text')=>({id,type,name,map,prompt:type==='model'?'根据授权资料完成任务，并提供依据。':'',skill:'',condition:'has_results',fallback:'',tool:type==='tool'?'search@1':'',model:'company-chat-standard',temperature:.3});
const edge=(from,to,port='next')=>({from,to,port});
function graph(kind){
 if(kind==='A')return {nodes:[node('in','input','场景输入'),node('data','data','检索条件','in.output'),node('search','tool','社区检索','data.output'),node('branch','condition','检索结果分支','search.output'),node('llm','model','推荐生成','search.output'),node('fallback','fallback','无结果 / 异常保底'),node('check','validate','引用与格式校验','llm.output'),node('out','output','推荐输出','check.output')],edges:[edge('in','data'),edge('data','search'),edge('search','branch'),edge('branch','llm','yes'),edge('branch','fallback','no'),edge('llm','check'),edge('check','out'),edge('fallback','out')]};
 if(kind==='B')return {nodes:[node('in','input','内容输入'),node('llm','model','政策分类判断','in.output'),node('check','validate','类别与理由校验','llm.output'),node('out','output','结构化结论','check.output'),node('fallback','fallback','转人工复核')],edges:[edge('in','llm'),edge('llm','check'),edge('check','out'),edge('fallback','out')]};
 return {nodes:[node('in','input','问题输入'),node('ctx','context','会话上下文','in.output'),node('kb','knowledge','售后知识检索','ctx.output'),node('llm','model','引用回答','kb.output'),node('check','validate','引用与格式校验','llm.output'),node('out','output','客服辅助回答','check.output'),node('fallback','fallback','提示客服核实')],edges:[edge('in','ctx'),edge('ctx','kb'),edge('kb','llm'),edge('llm','check'),edge('check','out'),edge('fallback','out')]};
}
function config(kind){let g=graph(kind);g.nodes.filter(n=>['model','tool','knowledge','validate','service'].includes(n.type)).forEach(n=>n.fallback='fallback');g.nodes.find(n=>n.type==='model').skill=kind==='A'?'outfit-writing@1':kind==='C'?'service-answer@1':'';return {mode:kind==='A'?'flow':'simple',preset:kind==='B'?'single':'rag',execution:kind==='B'?'batch':'online',sessions:kind==='C',approval:kind==='B',gray:kind==='A',inputSchema:kind==='A'?'{"text":"string","budget":"number"}':'{"text":"string"}',outputSchema:kind==='B'?'{"category":"string","reason":"string"}':'{"answer":"string","references":"array"}',prompt:kind==='B'?'依据有效政策输出类别和理由，边界案例转人工。':'根据输入和授权资料回答，缺少依据时提示人工核实。',model:'company-chat-standard',temperature:.3,timeout:10,retries:1,knowledge:kind==='B'?'policy@1':kind==='C'?'kb@1':'',template:kind==='A'?'outfit@1':kind==='B'?'classify@1':'qa@1',skill:kind==='A'?'outfit-writing@1':kind==='C'?'service-answer@1':'',service:'',rule:false,strategy:'热门优先',...g};}
function initial(){let s={schema:13,role:'业务编辑者',apps:[],assets:[{id:'policy@1',type:'policy',name:'社区政策',valid:true,text:'识别直接违规表达；边界内容转人工。'},{id:'policy@2',type:'policy',name:'社区政策更新',valid:true,text:'增加变体联系方式与隐晦引流识别。'},{id:'kb@1',type:'knowledge',name:'售后知识',valid:true,text:'普通商品符合条件时支持 7 天无理由退货。非质量问题运费由买家承担。'},{id:'kb@2',type:'knowledge',name:'售后知识更新',valid:true,text:'演示活动商品符合条件时支持 15 天无理由退货。非质量问题运费由买家承担。'},{id:'outfit-writing@1',type:'skill',name:'穿搭表达规范',valid:true,text:'给出三组建议并引用笔记，不编造同款。'},{id:'service-answer@1',type:'skill',name:'客服回答规范',valid:true,text:'先回答后解释并引用知识，无依据转人工。'},{id:'search@1',type:'tool',name:'社区笔记检索',valid:true,authorized:true,text:'只读检索，10 秒超时、最多一次重试。'},{id:'logistics@1',type:'tool',name:'物流查询',valid:true,authorized:true,text:'只读订单物流；不得退款。'}],templates:[],services:[],runs:[],sessions:[],batches:[],evalTasks:[],audit:[],samples:[],exposures:[],feedback:[],seq:0};
 for(const [i,name,owner] of [['A','社区穿搭灵感','林晓'],['B','生态守护','周宁'],['C','电商售后答疑','陈思远']]){let c=config(i);s.templates.push({id:c.template,name:i==='A'?'检索推荐':i==='B'?'分类判断':'知识问答',config:copy(c)});let version={id:'v1.0',revision:0,config:copy(c),time:'预置历史',report:{pass:true,dataset:'ds-'+i.toLowerCase()+'@1',rule:1,metrics:metrics(i,c),historical:true},approval:'通过'};s.apps.push({id:i,name,owner,kind:i,team:i+' 团队',draft:copy(c),revision:1,candidate:null,versions:[version],production:'v1.0',grayVersion:null,grayPercent:0,active:true,dataset:'ds-'+i.toLowerCase()+'@1',ruleRevision:1});}
 s.apps[1].versions[0].config.rule=true;s.apps[1].versions[0].report.metrics=metrics('B',s.apps[1].versions[0].config);s.apps[1].draft.knowledge='policy@2';return s;
}
function metrics(kind,c){if(kind==='B')return [['分类精确率',98.6,97,'%',true],['违规召回率',c.rule?99:96.8,98,'%',c.rule],['红线漏判',c.rule?0:1,0,'条',c.rule],['结构正确率',100,100,'%',true]];if(kind==='C')return [['回答正确率',97.2,95,'%',true],['引用有效率',100,100,'%',true],['无依据回答',0,0,'条',true],['多轮一致性',98,95,'%',true]];return [['推荐相关性',94.6,90,'%',true],['笔记有效率',100,100,'%',true],['安全通过率',100,100,'%',true],['P95 延迟',842,1000,'ms',true]];}
const deps=c=>[c.knowledge,c.template,c.skill,c.service,...c.nodes.flatMap(n=>[n.skill,n.tool])].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i);
function dependencyErrors(s,c){return deps(c).flatMap(id=>{let a=s.assets.find(x=>x.id===id)||s.templates.find(x=>x.id===id)||s.services.find(x=>x.id===id);return !a?[`依赖 ${id} 不存在`]:a.valid===false?[`依赖 ${id} 已失效`]:a.authorized===false?[`依赖 ${id} 无访问权限`]:[]})}
function check(c,s){let errors=[],add=(message,id='')=>errors.push({message,id});if(!c.prompt.trim())add('提示词必填');if(!c.model)add('模型必选');if(c.temperature<0||c.temperature>1)add('温度应为 0–1');if(c.timeout<1||c.timeout>60)add('超时应为 1–60 秒');for(const k of ['inputSchema','outputSchema']){try{let o=JSON.parse(c[k]);if(!o||Array.isArray(o)||typeof o!=='object'||!Object.keys(o).length||Object.values(o).some(v=>!['string','number','boolean','array','object'].includes(v)))add(k+' 字段类型不合法')}catch{add(k+' 必须为合法 JSON')}}
 if(c.mode==='service'){if(!s.services.some(x=>x.id===c.service))add('必须绑定已注册的版本化服务');dependencyErrors(s,c).forEach(x=>add(x));return errors;}
 let ids=c.nodes.map(n=>n.id),ins=c.nodes.filter(n=>n.type==='input'),outs=c.nodes.filter(n=>n.type==='output');if(ins.length!==1)add('流程必须有且仅有一个输入节点');if(!outs.length)add('流程缺少输出节点');if(new Set(ids).size!==ids.length)add('节点 ID 重复');
 for(const e of c.edges)if(!ids.includes(e.from)||!ids.includes(e.to))add('存在悬空连线',e.from);
 for(const n of c.nodes){if(!n.name.trim())add('节点名称必填',n.id);if(n.type==='model'&&!n.prompt.trim())add('模型节点提示词必填',n.id);if(n.type==='condition'&&!['has_results','is_logistics'].includes(n.condition))add('条件表达式不支持',n.id);if(n.type==='condition'&&['yes','no'].some(p=>c.edges.filter(e=>e.from===n.id&&e.port===p).length!==1))add('条件节点必须分别连接 yes / no 分支',n.id);if(n.type!=='condition'&&n.type!=='output'&&c.edges.filter(e=>e.from===n.id).length!==1)add('顺序节点需连接一个出口，不支持并行',n.id);if(['model','knowledge','tool','service','validate'].includes(n.type)&&!c.nodes.some(x=>x.id===n.fallback&&x.type==='fallback'))add('缺少有效异常出口',n.id);if(n.type!=='input'&&n.type!=='fallback'){let source=n.map.split('.')[0];if(source!=='input'&&(!ids.includes(source)||source===n.id))add('变量来源不存在或自引用',n.id);}if(n.type==='tool'&&!s.assets.some(x=>x.type==='tool'&&x.id===n.tool))add('工具未注册',n.id);}
 let inputFields={};try{inputFields=JSON.parse(c.inputSchema)}catch{}for(const n of c.nodes.filter(n=>!['input','fallback'].includes(n.type))){const [source,key]=n.map.split('.');if(source==='input'&&!Object.hasOwn(inputFields,key))add('输入变量字段未在契约中声明',n.id);if(source!=='input'&&ids.includes(source)){let visited=new Set();const reaches=id=>{if(id===n.id)return true;if(visited.has(id))return false;visited.add(id);return c.edges.filter(e=>e.from===id).some(e=>reaches(e.to))};if(!reaches(source))add('映射来源不是可达的上游节点',n.id);if(key!=='output')add('节点映射需使用 nodeId.output',n.id)}}
let seen=new Set(),visiting=new Set(),cycle=false;function walk(id){if(visiting.has(id)){cycle=true;return}if(seen.has(id))return;visiting.add(id);let n=c.nodes.find(x=>x.id===id);for(let e of c.edges.filter(e=>e.from===id))walk(e.to);if(n?.fallback)walk(n.fallback);visiting.delete(id);seen.add(id)}if(ins[0])walk(ins[0].id);if(cycle)add('存在循环，一期仅支持顺序和条件流程');for(let n of c.nodes)if(!seen.has(n.id))add('节点不可达',n.id);dependencyErrors(s,c).forEach(x=>add(x));return errors;}
function log(s,app,text){s.audit.unshift({id:++s.seq,appId:app.id,name:app.name,text,role:s.role,time:new Date().toLocaleString('zh-CN')})}
function save(s,a,c){if(s.role!=='业务编辑者')throw Error('请切换业务编辑者修改草稿');if(JSON.stringify(a.draft)!==JSON.stringify(c)){a.draft=copy(c);a.revision++;a.candidate=null;log(s,a,'草稿保存为 r'+a.revision+'，须重新固化与评测')}return a.revision;}
function freeze(s,a){if(s.role!=='业务编辑者')throw Error('只有业务编辑者可固化');let errors=check(a.draft,s);if(errors.length)throw Error(errors[0].message);let id='v1.'+(a.versions.reduce((m,v)=>Math.max(m,+v.id.split('.')[1]),0)+1);a.versions.push({id,revision:a.revision,config:copy(a.draft),report:null,approval:'未申请',time:new Date().toLocaleString('zh-CN')});a.candidate=id;log(s,a,'固化 '+id+' / r'+a.revision);return id;}
const version=(a,id)=>a.versions.find(v=>v.id===id);
function evaluate(s,a,id,fail=false){if(s.role!=='业务编辑者')throw Error('请切换业务编辑者执行评测');let v=version(a,id);if(!v)throw Error('候选版本不存在');v.reports=v.reports||[];if(v.report&&!v.reports.length)v.reports.push(copy(v.report));let m=metrics(a.kind,v.config),taskId='eval_'+(++s.seq);v.report={id:'report_'+(++s.seq),versionId:id,pass:!fail&&m.every(x=>x[4]),metrics:m,dataset:a.dataset,rule:a.ruleRevision,error:fail?'EVAL_TIMEOUT':'',time:new Date().toLocaleString('zh-CN')};v.reports.push(copy(v.report));v.approval='未申请';s.evalTasks=s.evalTasks||[];s.evalTasks.unshift({id:taskId,appId:a.id,appName:a.name,owner:a.owner||'未指定',versionId:id,datasetId:a.dataset,status:fail?'失败':'完成',pass:v.report.pass,reportId:v.report.id,time:v.report.time});log(s,a,id+' 评测'+(v.report.pass?'通过':'未通过'));return v.report;}
function gate(s,a,id,role=true){let v=version(a,id);if(!v)return ['尚未固化候选版本'];let reasons=dependencyErrors(s,v.config);if(check(v.config,s).length)reasons.push('静态检查未通过');if(!v.report?.pass)reasons.push(v.report?.error?'评测执行失败':'该版本未通过评测');if(v.report&&(v.report.dataset!==a.dataset||v.report.rule!==a.ruleRevision))reasons.push('数据集或准入规则已更新，需重评');if(v.config.approval&&v.approval!=='通过')reasons.push('指定审批尚未通过');if(role&&s.role!=='发布者')reasons.push('当前角色无发布权限');return reasons;}
function approve(s,a,id,decision){let v=version(a,id);if(!v)throw Error('版本不存在');if(!v.report?.pass||v.report.dataset!==a.dataset||v.report.rule!==a.ruleRevision||dependencyErrors(s,v.config).length)throw Error('先完成有效评测与依赖检查');if(decision==='申请'){if(s.role!=='业务编辑者')throw Error('业务编辑者申请审批');v.approval='待审批'}else{if(s.role!=='指定审批人'||v.approval!=='待审批')throw Error('需要指定审批人处理待审批版本');v.approval=decision}log(s,a,id+' 审批：'+v.approval);}
function deploy(s,a,id,ratio=100,fail=false){let reasons=gate(s,a,id);if(reasons.length)throw Error(reasons.join('；'));let v=version(a,id);if(ratio<100&&!v.config.gray)throw Error('版本未开启灰度能力');if(ratio<100&&!a.production)throw Error('首次上线没有稳定版本，请全量发布');if(fail)throw Error('模拟部署失败，生产流量保持不变');if(ratio===100){a.production=id;a.grayVersion=null;a.grayPercent=0}else{a.grayVersion=id;a.grayPercent=ratio}a.active=true;log(s,a,id+' 发布到生产 '+ratio+'%');}
function rollback(s,a,id){if(s.role!=='发布者')throw Error('当前角色无恢复权限');let v=version(a,id);if(!v)throw Error('恢复版本不存在');let errs=dependencyErrors(s,v.config);if(errs.length)throw Error(errs.join('；'));if(!v.report?.pass)throw Error('仅可恢复已验证版本');a.production=id;a.grayVersion=null;a.grayPercent=0;log(s,a,'回退到 '+id+'，恢复全部依赖；已有会话保持绑定');}
function route(a,user){if(!a.grayVersion)return a.production;let bucket=Array.from(user).reduce((n,c)=>n+c.charCodeAt(0),0)%100;return bucket<a.grayPercent?a.grayVersion:a.production;}
function execute(s,a,c,input,scenario='normal',meta={},only=null){let errs=only?[]:check(c,s);if(errs.length)throw Error(errs[0].message);if(!input?.trim())throw Error('输入不能为空');let accessErrors=dependencyErrors(s,c);if(accessErrors.length)throw Error(accessErrors.join('；'));let payload={text:input};if(input.trim().startsWith('{')){try{payload=JSON.parse(input)}catch{throw Error('输入 JSON 格式不合法')}let schema=JSON.parse(c.inputSchema);for(const [key,type] of Object.entries(schema)){if(!(key in payload))throw Error('缺少输入字段 '+key);if((type==='array'?!Array.isArray(payload[key]):typeof payload[key]!==type))throw Error('输入字段 '+key+' 类型不匹配')}if('budget' in payload&&payload.budget<=0)throw Error('预算必须大于 0')};let id='run_'+(++s.seq),steps=[],current=only||c.nodes.find(n=>n.type==='input')?.id,output='',seen=new Set(),outputs={},status='成功',error='',previous=payload.text||input,reference=c.knowledge;
 if(c.mode==='service'&&!only){let service=s.services.find(x=>x.id===c.service);steps.push({id:'external',name:'外部接口调用边界',input,output:{answer:'外部服务模拟返回',externalTraceId:'ext_'+s.seq,service:c.service},duration:428,error:''});output='受控服务返回模拟结果；内部节点不可见。'}else while(current&&!seen.has(current)){seen.add(current);let n=c.nodes.find(x=>x.id===current);if(!n)break;let [source,key]=n.map.split('.');if(n.type!=='input'&&n.type!=='fallback'&&!only){let mapped=source==='input'?payload[key]:outputs[source];if(mapped!==undefined)previous=copy(mapped)}let out=previous,err='',duration=42,port='next';
 if(n.type==='input')out=payload;if(n.type==='data')out={query:copy(previous),strategy:c.strategy};
 if(n.type==='context')out={text:input,history:meta.history||[]};
 if(n.type==='tool'){duration=218;if(scenario==='timeout'||scenario==='logistics_timeout'){err='TIMEOUT';out={error:err,attempts:2};duration=20000}else out=n.tool.startsWith('logistics')?{status:'运输中',tracking:'模拟物流记录'}:{notes:scenario==='empty'?[]:['N101','N102','N103']};}
 if(n.type==='condition'){port=n.condition==='is_logistics'?(/物流|快递|到哪/.test(input)?'yes':'no'):(Array.isArray(previous?.notes)&&previous.notes.length===0?'no':'yes');out={condition:n.condition,result:port==='yes',selected:port};}
 if(n.type==='knowledge'){out={snapshot:c.knowledge,text:s.assets.find(x=>x.id===c.knowledge)?.text||'',references:[c.knowledge]};if(scenario==='no_knowledge'){err='NO_EVIDENCE';out={error:err}}}
 if(n.type==='model'){duration=582;let knowledge=s.assets.find(x=>x.id===c.knowledge)?.text;out=a.kind==='B'?{category:c.rule?'违规':'待人工复核',reason:c.rule?'识别变体联系方式引流':'规则未覆盖，需人工核实',policyVersion:c.knowledge,needsHumanReview:true}:a.kind==='C'?{answer:knowledge?(input.includes('运费')?'沿用本会话上下文，依据绑定快照：'+knowledge:knowledge):'未找到授权知识依据，请客服人工核实。',references:knowledge?[c.knowledge]:[],fallback:!knowledge}:{answer:'白色 T 恤搭浅蓝牛仔裤与帆布鞋。',notes:['N101 白 T 周末搭配','N102 牛仔裤轻松穿法','N103 帆布鞋出游记录']};}
 if(n.type==='fallback'){out={answer:scenario==='empty'?'暂无匹配笔记，可尝试调整场景或预算。':'服务暂不可用或依据不足，请人工核实。',fallback:true,notes:[]};status='已兜底'}
 if(n.type==='validate'&&scenario==='invalid_reference'){out={answer:'已移除失效笔记 N102',notes:['N101','N103']};error='INVALID_REFERENCE';status='降级成功'}
 if(err){error=err;status='已兜底'}steps.push({id:n.id,name:n.name,type:n.type,input:copy(previous),output:copy(out),duration,error:err,mapping:n.map,reference,skill:n.skill});outputs[n.id]=copy(out);previous=out;output=out;if(only)break;current=err?n.fallback:c.edges.find(e=>e.from===n.id&&e.port===port)?.to;
 }
 let r={id,appId:a.id,environment:meta.environment||'测试',versionId:meta.versionId||null,revision:meta.versionId?null:a.revision,sessionId:meta.sessionId||null,input,output,status,error,steps,dependencies:deps(c),config:copy(c),duration:steps.reduce((n,x)=>n+x.duration,0),time:new Date().toLocaleTimeString('zh-CN'),traceId:'trace_'+s.seq,...meta};s.runs.unshift(r);return r;}
function productionRun(s,a,input,user='user-zz',sessionId=null,scenario='normal'){if(!a.active||!a.production)throw Error('服务未上线或已停用，请转人工');let session=sessionId?s.sessions.find(x=>x.id===sessionId&&x.appId===a.id):null;if(session?.closed)throw Error('会话已结束，请新建');let id=session?.versionId||route(a,user),v=version(a,id);let errs=dependencyErrors(s,v.config);if(errs.length)throw Error(errs.join('；')+'，请转人工');if(v.config.sessions&&!session){session={id:'session_'+(++s.seq),appId:a.id,versionId:id,history:[],closed:false};s.sessions.push(session)}let r=execute(s,a,v.config,input,scenario,{environment:'生产',versionId:id,sessionId:session?.id||null,history:copy(session?.history||[])});if(session)session.history.push({input,output:copy(r.output)});return r;}
function batch(s,a,key,legacy=false){if(!key?.trim())throw Error('批次标识必填');if(!a.active)throw Error('服务已停用');let old=s.batches.find(b=>b.appId===a.id&&b.key===key);if(old){old.dedup++;return old}let v=version(a,legacy?'v1.0':a.production);if(!v||v.config.execution!=='batch')throw Error('生产版本未启用批量执行');let errs=dependencyErrors(s,v.config);if(errs.length)throw Error(errs.join('；'));let b={id:'batch_'+(++s.seq),key,appId:a.id,versionId:v.id,policy:v.config.knowledge,dedup:0,paused:false,items:Array.from({length:5},(_,i)=>({id:'content_'+(i+1),status:legacy&&i>1?'待处理':i>2?'失败':'成功',error:legacy&&i>1?'':i===3?'TIMEOUT':i===4?'INVALID_FORMAT':'',attempts:legacy&&i>1?0:1,result:legacy&&i>1||i>2?null:{category:i%2?'违规':'正常',reason:'模拟人工辅助分类',policy:v.config.knowledge}}))};s.batches.unshift(b);b.items.filter(i=>i.attempts>0).forEach(i=>recordBatchItem(s,a,b,i));log(s,a,'提交 '+b.id+'，绑定 '+v.id+' / '+b.policy);return b;}
function retry(s,a,b){if(b.appId!==a.id||!a.active||b.paused)throw Error('任务暂停或服务停用，不能重试');let errs=dependencyErrors(s,version(a,b.versionId).config);if(errs.length)throw Error(errs.join('；'));for(let item of b.items.filter(x=>x.status==='失败')){item.status='成功';item.attempts++;item.error='';item.result={category:'待人工复核',reason:'失败项模拟重试完成',policy:b.policy};recordBatchItem(s,a,b,item)}log(s,a,b.id+' 仅重试失败项，按内容 ID 去重');}
function invalidate(s,id){let asset=s.assets.find(x=>x.id===id);if(!asset)throw Error('资产不存在');asset.valid=false;for(let b of s.batches.filter(b=>b.policy===id)){b.paused=true;for(let i of b.items)if(i.status==='待处理'||i.status==='失败')i.status='暂停'}s.audit.unshift({name:'资产中心',text:id+' 已失效，相关调用与恢复被阻止',role:s.role,time:new Date().toLocaleString('zh-CN')});}
function logistics(c){if(c.nodes.some(n=>n.id==='intent'))return;c.mode='flow';let prev=c.nodes.find(n=>n.type==='context')||c.nodes.find(n=>n.type==='input'),kb=c.nodes.find(n=>n.type==='knowledge'),checkNode=c.nodes.find(n=>n.type==='validate');c.edges=c.edges.filter(e=>e.from!==prev.id);let n=node('logistics','tool','授权物流查询','intent.output');n.tool='logistics@1';n.fallback='fallback';let branch=node('intent','condition','是否查询物流',prev.id+'.output');branch.condition='is_logistics';c.nodes.push(branch,n);c.edges.push(edge(prev.id,'intent'),edge('intent','logistics','yes'),edge('intent',kb.id,'no'),edge('logistics',checkNode.id));}
function recordBatchItem(s,a,b,item){let v=version(a,b.versionId),id='run_'+(++s.seq);item.runId=id;s.runs.unshift({id,appId:a.id,environment:'生产',versionId:b.versionId,taskId:b.id,itemId:item.id,input:item.id,output:copy(item.result),status:item.status,error:item.error,steps:[{id:'batch-item',name:'批处理条目执行边界',input:{contentId:item.id,policy:b.policy},output:copy(item.result),error:item.error,duration:item.error?10000:1240}],dependencies:deps(v.config),duration:item.error?10000:1240,time:new Date().toLocaleTimeString('zh-CN'),traceId:'trace_'+s.seq,config:copy(v.config)});}
function feedback(s,exposureId,type,eventId){if(!['click','adopt'].includes(type))throw Error('未知业务事件类型');let ex=s.exposures.find(x=>x.id===exposureId);if(!ex)throw Error('曝光不存在，拒绝无法归因的事件');if(!eventId?.trim())throw Error('事件 ID 必填');let old=s.feedback.find(x=>x.id===eventId);if(old)return {dedup:true,event:old};let event={id:eventId,exposureId,type,appId:ex.appId,versionId:ex.versionId,experiment:ex.experiment,user:ex.user};s.feedback.push(event);return {dedup:false,event};}
root.Engine={feedback,copy,types,node,edge,initial,config,graph,metrics,deps,check,dependencyErrors,log,save,freeze,version,evaluate,gate,approve,deploy,rollback,route,execute,productionRun,batch,retry,invalidate,logistics};
})(typeof window!=='undefined'?window:globalThis);


