const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const context={document:{querySelector(){return null},addEventListener(){}},window:{addEventListener(){}},flow(){},render(){},editNode(){},S:{},appId:'A'};
vm.createContext(context);
vm.runInContext(fs.readFileSync('dist/canvas.js','utf8'),context);
const run=s=>vm.runInContext(s,context);
run(`var v={x:30,y:40,zoom:.75}; var p=CanvasMath.point(250,190,v); var z=CanvasMath.zoomAt(v,1.5,250,190); var q=CanvasMath.point(250,190,z);`);
assert.ok(run('Math.abs(p.x-q.x)<1e-9 && Math.abs(p.y-q.y)<1e-9'));
assert.equal(run('CanvasMath.zoomAt(v,100,0,0).zoom'),2);
assert.equal(run('CanvasMath.zoomAt(v,.001,0,0).zoom'),.25);
run(`var c={nodes:[{id:'in',type:'input'},{id:'model',type:'model'},{id:'branch',type:'condition'},{id:'out',type:'output'},{id:'fail',type:'fallback'}],edges:[{from:'in',to:'model',port:'next'}]};`);
assert.equal(run("CanvasMath.connectionError(c,'model','branch','next')"),'');
assert.equal(run("CanvasMath.connectionError(c,'model','fail','error')"),'');
for(const args of ["'in','out','next'","'model','model','next'","'model','in','next'","'out','model','next'","'model','out','error'","'branch','out','next'"])assert.ok(run(`CanvasMath.connectionError(c,${args})`));
run("c.edges.push({from:'model',to:'branch',port:'next'})");
assert.ok(run("CanvasMath.connectionError(c,'branch','model','yes')"));
assert.equal(run("CanvasMath.connectionError(c,'branch','out','yes')"),'');
assert.equal(run("CanvasMath.connectionError(c,'branch','out','no')"),'');
const before=run('JSON.stringify(c)');run("canvasPosition(c.nodes[0],0).x=123;canvasState().view.zoom=.5");
assert.equal(run('JSON.stringify(c)'),before);
console.log('PASS: anchored zoom, limits, branch/error ports, duplicate/cycle rejection and layout/config isolation.');
